# Generated by Django 4.1 on 2022-08-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ForecastTabla",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date_Create", models.DateField(auto_now_add=True)),
                ("usuario", models.CharField(blank=True, max_length=10, null=True)),
                ("tipo", models.CharField(blank=True, max_length=10, null=True)),
                ("codigo", models.CharField(max_length=7)),
                ("Fecha", models.DateField()),
                ("Dia", models.IntegerField()),
                ("Mes", models.IntegerField()),
                ("CONTACTOS_TLV", models.FloatField()),
                ("CONTACTOS_WEB", models.FloatField()),
                ("CONTACTOS_IMP", models.FloatField()),
                ("BB_CATEGORIA", models.FloatField()),
                ("DTV_PROGRAMACION", models.FloatField()),
                ("DTV_TOH", models.FloatField()),
                ("MACRO_IPC", models.FloatField()),
                ("MACRO_USD", models.FloatField()),
                ("GT_DEPOR_COPA_ARGENTINA", models.FloatField()),
                ("GT_DEPOR_CHAMPIONS_LEAGUE", models.FloatField()),
                ("GT_DEPOR_REAL_VS_BARZA", models.FloatField()),
                ("GT_DEPOR_RACING_VS_INDEP", models.FloatField()),
                ("GT_DEPOR_MUNDIAL_FUTBOL", models.FloatField()),
                ("GT_DEPOR_ROLAND_GARROS", models.FloatField()),
                ("GT_DEPOR_WIMBLEDON", models.FloatField()),
                ("PRECIO_DIRECTV", models.FloatField()),
                ("DTV_CTA", models.FloatField()),
                ("COMP_TELECENTRO", models.FloatField()),
                ("CBV_TOH", models.FloatField()),
                ("CBV_DEPORTE", models.FloatField()),
                ("TEL_GOOGLETRENDS", models.FloatField()),
                ("Forecast_ACTIVACIONES_POS", models.FloatField()),
            ],
            options={
                "ordering": ["-Date_Create"],
            },
        ),
        migrations.CreateModel(
            name="ForecastTablaManu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date_Create", models.DateField(auto_now_add=True)),
                ("usuario", models.CharField(blank=True, max_length=10, null=True)),
                ("tipo", models.CharField(max_length=10)),
                ("codigo", models.CharField(max_length=7)),
                ("Fecha", models.CharField(blank=True, max_length=15, null=True)),
                ("Dia", models.IntegerField()),
                ("Mes", models.IntegerField()),
                ("CONTACTOS_TLV", models.FloatField()),
                ("CONTACTOS_WEB", models.FloatField()),
                ("CONTACTOS_IMP", models.FloatField()),
                ("BB_CATEGORIA", models.FloatField()),
                ("DTV_PROGRAMACION", models.FloatField()),
                ("DTV_TOH", models.FloatField()),
                ("MACRO_IPC", models.FloatField()),
                ("MACRO_USD", models.FloatField()),
                ("GT_DEPOR_COPA_ARGENTINA", models.FloatField()),
                ("GT_DEPOR_CHAMPIONS_LEAGUE", models.FloatField()),
                ("GT_DEPOR_REAL_VS_BARZA", models.FloatField()),
                ("GT_DEPOR_RACING_VS_INDEP", models.FloatField()),
                ("GT_DEPOR_MUNDIAL_FUTBOL", models.FloatField()),
                ("GT_DEPOR_ROLAND_GARROS", models.FloatField()),
                ("GT_DEPOR_WIMBLEDON", models.FloatField()),
                ("PRECIO_DIRECTV", models.FloatField()),
                ("DTV_CTA", models.FloatField()),
                ("COMP_TELECENTRO", models.FloatField()),
                ("CBV_TOH", models.FloatField()),
                ("CBV_DEPORTE", models.FloatField()),
                ("TEL_GOOGLETRENDS", models.FloatField()),
                ("Forecast_ACTIVACIONES_POS", models.FloatField()),
            ],
            options={
                "ordering": ["-Date_Create"],
            },
        ),
    ]
