# Generated by Django 4.1 on 2022-09-06 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("RFapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forecasttabla",
            options={"ordering": ["Date_Create"]},
        ),
        migrations.AlterModelOptions(
            name="forecasttablamanu",
            options={"ordering": ["Date_Create"]},
        ),
    ]
